  name: Validate, Package, Deploy
  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
#    validate:
    package:
      name: Package
      if: ${{ github.ref_name != 'no_ci' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '20'
            check-latest: false
            cache: 'gradle'
        - run: |
            ./gradlew build
        #    publish: