  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
#    validate:
    package:
      runs-on: ubuntu-latest
      steps:
        - run: |
            ./gradlew build
        #    publish: